# Generated by Django 5.1.3 on 2024-11-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dciywsode/image/upload/v1732574415/g6uhjai0rgmeufx99dud.png', null=True, upload_to='image/'),
        ),
    ]
