# Generated by Django 5.1.3 on 2025-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audio_created_at_audio_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='created_at',
        ),
    ]
