# Generated by Django 5.1.3 on 2025-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_remove_audio_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file_hash',
            field=models.CharField(default='dsdassd', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
