# Generated by Django 5.1.3 on 2025-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='genre',
        ),
        migrations.AddField(
            model_name='image',
            name='color_depth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
