# Generated by Django 5.1.3 on 2025-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_created_at_image_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
    ]
