# Generated by Django 5.1.3 on 2025-01-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_audio_codec_alter_video_bitrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
