# Generated by Django 5.1.3 on 2025-01-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
