# Generated by Django 5.1.3 on 2025-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
