# Generated by Django 5.1.3 on 2025-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_video_created_at_video_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
