# Generated by Django 5.1.3 on 2025-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_remove_video_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_hash',
            field=models.CharField(default='dfdfgdbg', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
