# Generated by Django 5.1.3 on 2025-03-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_video_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Processando'), (1, 'Completo')], default=0),
        ),
    ]
